# Generated by Django 3.1.7 on 2021-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
