# Generated by Django 3.1.7 on 2021-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_education_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
