# Generated by Django 3.1.7 on 2021-04-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20210406_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
