# Generated by Django 3.1.7 on 2021-04-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20210406_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='subject_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
