# Generated by Django 3.1.7 on 2021-04-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_education_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_language', models.CharField(blank=True, max_length=254, null=True)),
                ('backend_framwork', models.CharField(blank=True, max_length=254, null=True)),
                ('frontend_language', models.CharField(blank=True, max_length=254, null=True)),
                ('frontend_framwork', models.CharField(blank=True, max_length=254, null=True)),
                ('database', models.CharField(max_length=254)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
