# Generated by Django 3.1.7 on 2021-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='prifileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
