# Generated by Django 3.2.6 on 2021-08-31 16:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_alter_about_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
