# Generated by Django 3.2.6 on 2021-09-01 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0002_author_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
