# Generated by Django 3.2.6 on 2021-09-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0004_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articate_image',
            field=models.ImageField(height_field='image_height', max_length=255, upload_to='blog_images', width_field='image_width'),
        ),
    ]
