# Generated by Django 3.2.6 on 2021-09-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0005_alter_article_articate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articate_image',
            field=models.ImageField(max_length=255, upload_to='blog_images'),
        ),
    ]
