# Generated by Django 3.2.6 on 2021-09-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0008_alter_article_articate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articate_image',
            field=models.ImageField(upload_to='blog_images/%Y/%m/', verbose_name='Image'),
        ),
    ]
