# Generated by Django 3.2.6 on 2021-09-02 18:15

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0010_alter_article_articate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articate_image',
            field=stdimage.models.StdImageField(upload_to='blog_images/%Y/%m/'),
        ),
    ]
