# Generated by Django 3.2.6 on 2021-09-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0012_author_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=264, null=True),
        ),
    ]
