# Generated by Django 3.2.6 on 2021-09-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0013_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'On Review'), (3, 'Publish')], default=0, max_length=1, verbose_name='Publication Status'),
        ),
    ]
