# Generated by Django 3.2.6 on 2021-09-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0015_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
