# Generated by Django 3.2.6 on 2021-09-11 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_App', '0016_alter_article_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='auth.user'),
            preserve_default=False,
        ),
    ]
