# Generated by Django 3.2.6 on 2021-09-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0017_auto_20210911_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Pending'), ('2', 'On Review'), ('3', 'Publish')], default='0', max_length=1, verbose_name='Publication Status'),
        ),
    ]
